import pandas as pd
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px
from dash.dependencies import Input, Output
import plotly.graph_objects as go
import plotly.io as plt_io
import dash_auth

USERNAME_PASSWORD_PAIRS=[['username','password'],['jamesbond','007']]

# create our custom_dark theme from the plotly_dark template
plt_io.templates["custom_dark"] = plt_io.templates["plotly_dark"]

# set the paper_bgcolor and the plot_bgcolor to a new color
plt_io.templates["custom_dark"]['layout']['paper_bgcolor'] = '#30404D'
plt_io.templates["custom_dark"]['layout']['plot_bgcolor'] = '#30404D'

# you may also want to change gridline colors if you are modifying background
plt_io.templates['custom_dark']['layout']['yaxis']['gridcolor'] = '#4f687d'
plt_io.templates['custom_dark']['layout']['xaxis']['gridcolor'] = '#4f687d'

df=pd.DataFrame({
"Session Years":["2010-2011",
                 "2011-2012",
                 "2012-2013",
                 "2013-2014",
                 "2014-2015",
                 "2015-2016",
                 "2016-2017",
                 "2017-2018",
                 "2018-2019",
                 "2019-2020",
                 "2020-2021"],
"Revenue Receipts":[783833,
751437,
871828,
1014724,
1101472,
1195025,
1374203,
1435233,
1552916,
1850101,
2020926],
"Capital Receipts":[408857,
551730,
531140,
544723,
562201,
595748,
600991,
706742,
762197,
848451,
1021304],
"Total Receipts":[1197328,
                  1304365,
                  1410372,
                  1559447,
                  1663673,
                  1790783,
                  1975194,
                  2141975,
                  2315113,
                  2698552,
                  3042230]})

df2=pd.DataFrame({"Ministry":["Ministry of Agriculture and Farmers' Welfare",
                   "Department of Atomic Energy",
                   "Ministry of Ayurveda, Yoga and Naturopathy, Unani, Siddha and Homoeopathy (Ayush)",
                   "Ministry of Chemicals and Fertilisers",
                   "Ministry of Civil Aviation",
                   "Ministry of Coal",
                   "Ministry of Commerce and Industry",
                   "Ministry of Communications",
                   "Ministry of Consumer Affairs, Food and Public Distribution",
                   "Ministry of Corporate Affairs",
                   "Ministry of Culture",
                   "Ministry of Defence",
                   "Ministry of Development of North Eastern Region",
                   "Ministry of Earth Sciences",
                   "Ministry of Electronics and Information Technology",
                   "Ministry of Environment, Forests and Climate Change",
                   "Ministry of External Affairs",
                   "Ministry of Finance ",
                   "Ministry of Fisheries, Animal Husbandry and Dairying",
                   "Ministry of Food Processing Industries",
                   "Ministry of Health and Family Welfare",
                   "Ministry of Heavy Industries and Public Enterprises",
                   "Ministry of Home Affairs",
                   "Ministry of Housing and Urban Affairs",
                   "Ministry of Human Resource Development",
                   "Ministry of Information and Broadcasting",
                   "Ministry of Jal Shakti",
                   "Ministry of Labour and Employment",
                   "Ministry of Law and Justice",
                   "Ministry of Micro, Small and Medium Enterprises",
                   "Ministry of Mines",
                   "Ministry of Minority Affairs",
                   "Ministry of New and Renewable Energy",
                   "Ministry of Panchayati Raj",
                   "Ministry of Parliamentary Affairs",
                   "Ministry of Personnel, Public Grievances and Pensions",
                   "Ministry of Petroleum and Natural Gas",
                   "Ministry of Planning",
                   "Ministry of Power",
                   "The President, Parliament, Union Public Service Commission and the Secretariat of the Vice President",
                   "Ministry of Railways",
                   "Ministry of Road Transport and Highways",
                   "Ministry of Rural Development",
                   "Ministry of Science and Technology",
                   "Ministry of Shipping",
                   "Ministry of Skill Development and Entrepreneurship",
                   "Ministry of Social Justice and Empowerment",
                   "Department of Space",
                   "Ministry of Statistics and Programme Implementation",
                   "Ministry of Steel",
                   "Ministry of Textiles",
                   "Ministry of Tourism",
                   "Ministry of Tribal Affairs",
                   "Ministry of Women and Child Development",
                   "Ministry of Youth Affairs and Sports"],
"Revenue Receipts":[142712.03,
           8884.44,
           2122.08,
           71889.69,
           3771.74,
           882.61,
           10668.87,
           55150.8,
           123283.01,
           675.62,
           3057.57,
           352823,
           2330.14,
           1898,
           6524.03,
           2942.45,
           16014.43,
           1122911.74,
           4048.26,
           1232.94,
           66046.1,
           954.5,
           151464.9,
           28890.89,
           97084.52,
           4361.65,
           30092.47,
           12021.49,
           2577.61,
           7513.2,
           1587.04,
           4868.98,
           5701,
           900.94,
           50.52,
           1645.28,
           41994,
           649.22,
           14792.54,
           1641,
           2215.63,
           9848.51,
           122298.43,
           14362.49,
           1715,
           2923.03,
           10882.95,
           5704.2,
           5426.05,
           100,
           3463.76,
           2499.83,
           7260.99,
           30007.09,
           2775.9],
"Capital Receipts":[50.32,
           9344.5,
           0,
           7.23,
           25.97,
           0,
           2156,
           26806.27,
           1252.42,
           52,
           92.29,
           118555,
           718.59,
           172,
           375,
           157.55,
           1332.28,
           46025.6,
           65.87,
           0,
           1065.7,
           559.63,
           15785.43,
           21149.01,
           2227,
           13.56,
           386.02,
           44,
           201,
           59,
           114.36,
           160.02,
           52,
           0,
           0,
           148.26,
           907,
           0.78,
           1082.28,
           0,
           70000,
           81974.71,
           100,
           110.8,
           85,
           79.18,
           546.01,
           7775.27,
           17.95,
           0,
           51.03,
           0,
           150.01,
           0.01,
           51.02],
"Amount Allocated":[142762.35,
         18228.94,
         2122.08,
         71896.92,
         3797.71,
         882.61,
         12824.87,
         81957.07,
         124535.43,
         727.62,
         3149.86,
         471378,
         3048.73,
         2070,
         6899.03,
         3100,
         17346.71,
         1168937.34,
         4114.13,
         1232.94,
         67111.8,
         1514.13,
         167250.33,
         50039.9,
         99311.52,
         4375.21,
         30478.49,
         12065.49,
         2778.61,
         7572.2,
         1701.4,
         5029,
         5753,
         900.94,
         50.52,
         1793.54,
         42901,
         650,
         15874.82,
         1641,
         72215.63,
         91823.22,
         122398.43,
         14473.29,
         1800,
         3002.21,
         11428.96,
         13479.47,
         5444,
         100,
         3514.79,
         2499.83,
         7411,
         30007.1,
         2826.92],
})

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = dash.Dash(__name__)
auth=dash_auth.BasicAuth(app,USERNAME_PASSWORD_PAIRS)
server=app.server

colors = {
    'background': '#000000',
    'text': '#CCCCFF'
}

fig=px.line(df,x="Session Years",y="Total Receipts",title="Union Budget Over the Last 10 Years")
fig.update_traces(mode="lines+markers")
fig.update_layout(
    plot_bgcolor=colors['background'],
    paper_bgcolor=colors['background'],
    font_color=colors['text'])
#fig.show()

fig2=px.pie(df2,values="Amount Allocated",names="Ministry",title="Ministry Wise Allocation of Union Budget for Session 2020-21",height=700,color_discrete_sequence=px.colors.sequential.Agsunset)
fig2.update_traces(textposition='inside',insidetextorientation='horizontal')
fig2.update_layout(uniformtext_minsize=12, uniformtext_mode='hide',plot_bgcolor=colors['background'],paper_bgcolor=colors['background'],font_color=colors['text'])
#fig2.show()

app.layout = html.Div(style={'backgroundColor': colors['background']},
    children=[html.Div([
    html.H1(children="Indian Union Budget",style={'textAlign': 'center', 'color': '#A569BD'}),
    html.H3(children="According to Article 112 of the Indian Constitution, the Union Budget of a year, also referred to as the annual financial statement, is a statement of the estimated receipts and expenditure of the government for that particular year. Union Budget keeps the account of the government's finances for the fiscal year that runs from 1st April to 31st March. Union Budget is classified into Revenue Budget and Capital Budget.",style={'color': '#FFFFFF'}),
    html.H3(children="What is the Indian Union Budget?",style={'textAlign': 'left', 'color': '#000000'}),
    html.H2(children="Union Budget Trend Over the Last 10 Years",style={'textAlign': 'center', 'color': '#8EA9F1'}),
    html.H3(children="The following line chart displays the increasing trend of the Indian Union Budget between the years 2010-2021. The x-axis represents the session years and the y-axis represents the budget allocated (in Rupee crores). Clicking on the dropdown will also allow you to see the trend of the Revenue and Capital Receipts.",style={'textAlign': 'left', 'color': '#FFFFFF'}),
    html.H3(children="What is the Indian Union Budget?",style={'textAlign': 'left', 'color': '#000000'}),
    html.Label("Which line chart would you like to see?",style={'margin-right': '2em', 'color': '#A569BD','font_size':'30'}),
    html.Div(children=dcc.Dropdown(
        id='line_dropdown',
        options=[{'label':'Revenue Receipts-\n Revenue budget includes the government\'s revenue receipts and expenditure. There are two kinds of revenue receipts - tax and non-tax revenue. Revenue expenditure is the expenditure incurred on day to day functioning of the government and on various services offered to citizens. If revenue expenditure exceeds revenue receipts, the government incurs a revenue deficit.','value':df["Revenue Receipts"]},
                 {'label':'Capital Receipts-\n Capital Budget includes capital receipts and payments of the government. Loans from public, foreign governments and RBI form a major part of the government\'s capital receipts. Capital expenditure is the expenditure on development of machinery, equipment, building, health facilities, education etc. Fiscal deficit is incurred when the government\'s total expenditure exceeds its total revenue.','value':df["Capital Receipts"]},
                 {'label':'Total Receipts','value':df["Total Receipts"]}],
        placeholder="Select",
        value="Total Receipts",
        multi=False,
        clearable=False,
    )
    ),
    ]),
     html.Div([
        dcc.Graph(id='graph1',figure=fig),
        html.Div(children="Session Years",style={'textAlign': 'center', 'color': '#A569BD'})
        ]),
        html.Div([
        html.H1(children="What is the Indian Union Budget?",style={'textAlign': 'left', 'color': '#000000'}),
        html.H2(children="Budget Allocation for the Year 2020-21",style={'textAlign': 'center', 'color': '#8EA9F1'}),
        html.H3(children="The following chart displays how the Indian Union Budget for the session 2020-2021 has been allocated amongst various ministries and departments. Hovering over each slice will give us the name of the ministry/dept, the amount allocated to it and its respective percentage of the whole budget. The following customisations are possible with the pie chart:",style={'textAlign': 'left', 'color': '#FFFFFF'}),
        html.H3(children="1. Clicking once on the relevant minstry/dept from the legend will remove it from the pie chart",style={'textAlign': 'left', 'color': '#FFFFFF'}),
        html.H3(children="2. Clicking twice on the relevant ministry/dept from the legend will isolate it. We can then further click once on other ministries/depts that we want and they will get added to the pie chart",style={'textAlign': 'left', 'color': '#FFFFFF'}),
        dcc.Graph(id='graph2',
                  figure=fig2)
                  ])

])

@app.callback(
    Output(component_id='graph1', component_property='figure'),
    [Input(component_id='line_dropdown', component_property='value')]
)

def update_graph(line_dropdown):
    fig=px.line(df,x=df["Session Years"],y=line_dropdown,height=600,title="Union Budget Over the Last 10 Years")
    fig.update_traces(mode="lines+markers")
    fig.update_layout(
        margin=dict(l=30, r=30, t=30, b=30),
        plot_bgcolor=colors['background'],
        paper_bgcolor=colors['background'],
        font_color=colors['text'],
        xaxis_title="Session Years",
        yaxis_title="Union Budget (in Rupee Crores)",
        )
    fig.layout.template = 'custom_dark'
    return (fig)

if __name__ == '__main__':
    app.run_server(debug=True)
